### ISSUE TITLE
ember-cli module

### ISSUE THREAD

**Issue by aexmachina** [chrisfarber/ember-breadcrumbs#12]
Hi there, this module looks good except that `Ember.Handlebars.compile()` isn't included in a production build of Ember.js. I'm thinking of submitting a PR that turns this into an ember-cli addon which would allow the template to be compiled with the rest of the app's template. This would also make it easier for people to override the template - they would just copy the template into their own app.

Are you open this? Any thoughts/suggestions?

**Comment by chrisfarber** [comment]
Refactoring this into an ember-cli addon was actually already on my list of tasks to accomplish. It definitely appears that doing so would solve all the issues other people have been having. If you want to tackle this before me, I'll merge it.

It also looks like it'll give a good framework for getting some tests written, too. I wish ember-cli had addons when I originally looked to open source this.

**Comment by aexmachina** [comment]
Excellent, I'm on it already. It's not too hard for me because I just did this for another pre-ember-cli module ([ember-feature-flags](https://github.com/kategengler/ember-feature-flags)). PR on its way!

**Comment by aexmachina** [comment]
Hey, just wondering whether you want to keep using CoffeeScript? I like CoffeeScript but stopped using it a while ago because no support for ES6 modules, and ES6 syntax fixes most of the issues that I had with JavaScript.

It's fine to keep it but it does introduce a compile step in developing the addon, unless we require coffee-script to be added to the Broccoli pipeline for consumers of the addon.

**Comment by aexmachina** [comment]
I've created [the PR](https://github.com/chrisfarber/ember-breadcrumbs/pull/13).

I realise now that we actually need some features that aren't provided:

1. Multiple bread crumbs from a single route/controller
2. Ability to specify the model to be used for a bread crumb

So what I'm thinkig is to change the `breadCrumb` and `breadCrumbPath` properties to a single `breadCrumbs` property that can be used in two ways:

- An array of strings
- An array of objects in the form `{title: 'Foo', path: 'foo.bar', model: modelOrId, params: hashOfParams}`

We can keep the old properties but I'm inclined to suggest we remove them and provide information about how to upgrade (it's a *very* simple upgrade path).

Let me know your thoughts. I'm going to go ahead and do this on my fork anyway because we need it but hopeful you're happy to merge this back in as well.

**Comment by aexmachina** [comment]
I've submitted [another PR](https://github.com/chrisfarber/ember-breadcrumbs/pull/14) which adds the ability for a controller to provide multiple bread crumbs.

**Comment by chrisfarber** [comment]
I still prefer CoffeeScript, but it's too much of a pain to use it with the Ember ecosystem. I converted everything to JS.

Thanks for your work setting up the ember-cli addon infrastructure!

Regarding multiple crumbs per controller, I think there is a reasonable need for this. I'm not sure what the best API to accomplish this is quite yet. I'd like to make sure that, however it gets implemented, it's hard for users to add multiple crumbs in a way that would break live-updating via bindings. I'll think about this a bit.

**Comment by aexmachina** [comment]
Yeah no problem. I love CoffeeScript, but I tried just using JavaScript a while ago and have found it to be fine. As long as you've got ES6 syntax it's great.

Let's close this issue and continue the discussion of multiple breadcrumbs over on #14.
