### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by carlbennettnz** [chrisfarber/ember-breadcrumbs#17]
```
$ ember install:addon ember-breadcrumbs
version: 0.1.2
The specified command install:addon is invalid, for available options see ember help.
```

Is there a step missing from the README?

**Comment by chrisfarber** [comment]
The `install:addon` task was added in a newer ember-cli version. (I think it was added in 0.1.5).

You can upgrade your project's version of ember-cli, or just use `npm install --save-dev ember-breadcrumbs`
