### ISSUE TITLE
Using this without Ember-cli

### ISSUE THREAD

**Issue by copasetickid** [chrisfarber/ember-breadcrumbs#18]
If I'm not using ember-cli, how can mirror the app inject that you're doing to get this to run in my application?

**Comment by chrisfarber** [comment]
My best advice is to either copy the source directly into your ember app's source or start using ember-cli.

Trying to build/include plugins for Ember without ember-cli's addons is difficult and has some inherent difficulties.

This plugin was originally written before ember-cli's addons, and there were numerous issues relating to the default template and customizing.
