### ISSUE TITLE
Error while processing route:  Assertion Failed: You must use Ember.set() to set the `controller` property

### ISSUE THREAD

**Issue by msalahz** [chrisfarber/ember-breadcrumbs#23]
I had this issue since last week and It was frustrating investigating it until it gone when I uninstalled ember breadCrumb.
the problem was related to observe controller object.
for reference : https://github.com/emberjs/ember.js/pull/9767

**Comment by chrisfarber** [comment]
Could you try 0.1.3 and let me know if that fixes the issue?

**Comment by msalahz** [comment]
Where is the change log for the new release?

**Comment by msalahz** [comment]
@chrisfarber , I installed v0.1.3 and it's not generating this issue. thanks
