### ISSUE TITLE
Going from ember-cli 0.2.0 to 0.2.1 generates an error

### ISSUE THREAD

**Issue by damiencaselli** [chrisfarber/ember-breadcrumbs#24]
Hi!

I have no particular setup, but since I upgraded to `ember-cli@0.2.1`, when I try to do any `ember` command the result is always the same:

```
The `ember-breadcrumbs` addon could not be found at `/path/to/some-ember-app/node_modules/ember-breadcrumbs
```

Downgrading embercli to `0.2.0` seems to do the trick.

I also went for cloning the `ember-breadcrumbs` repository, and running the tests with ember-cli@0.2.0 works just fine whereas ember-cli@0.2.1 returns almost the same error:

```
The `ember-breadcrumbs` addon could not be found at `/path/to/ember-breadcrumbs
```

I tried to figure what could generate the error in the last ember-cli version, but I couldn't find out.

**Comment by migbar** [comment]
Ditto for me. 

In my package.json:
    "ember-breadcrumbs": "^0.1.3"

ember-cli@0.2.0 was ok, but moving to 0.2.1 caused a problem.

**Comment by chrisfarber** [comment]
Thanks for the heads up, guys. I won't have time to dig into this for a few days, but I'd happily merge a pull request sooner than that.

**Comment by migbar** [comment]
@chrisfarber do you want a PR ? or is it easy enough for you to just remove it ? :)

**Comment by chrisfarber** [comment]
Ah, sorry, I didn't see you'd figured out the problem when I replied. (Did you edit your comment, or am I crazy?)

Anyhow, thanks. No need for a pull request, I can take care of it in a few hours.

**Comment by migbar** [comment]
You are not crazy ... ;)
I did edit the comment. Sorry for the confusion. 
PR is there in case you want it.

**Comment by chrisfarber** [comment]
Thank you!

**Comment by damiencaselli** [comment]
Yey! Thanks for the quick response.
