### ISSUE TITLE
Does this still work with Ember 1.11?

### ISSUE THREAD

**Issue by carlbennettnz** [chrisfarber/ember-breadcrumbs#28]
I don't know why it wouldn't, but for the life of me I can't get any breadcrumbs to show up. Can someone confirm for me please?

**Comment by chrisfarber** [comment]
Yes, it should work with Ember 1.11. If you're using version 0.1.5, try upgrading to 0.1.6.

**Comment by carlbennettnz** [comment]
Hmm, okay. I'm running 0.1.6.

Just in case I'm doing something really stupid here, here's my process so far:

`$ ember install ember-breadcrumbs`

An `ember-breadcrumbs` folder is now in `node_modules`.

I've added `{{bread-crumbs}}` to my application template.

My application controller, in its entirety, looks like this:

```javascript
import Ember from 'ember';

export default Ember.Controller.extend({
  breadCrumb: 'Home'
});
```

Any ideas?

**Comment by carlbennettnz** [comment]
I gave up, continued working on other things, and then eventually I looked and it was all working wonderfully. I have no idea what I changed to get it going. Oh well, thanks, and sorry for the bother :)
