### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by carlbennettnz** [chrisfarber/ember-breadcrumbs#42]
Could you release the latest changes as a new version on npm please? Just trying to get rid of deprecations.

**Comment by smvv** [comment]
+1

**Comment by haldiggs** [comment]
you mean this? I hadn't looked at the newest version but if it handles this I'm a +1 :-)

DEPRECATION: The `initialize` method for Application initializer 'ember-breadcrumbs' should take only one argument

**Comment by meliborn** [comment]
any news?

**Comment by denchen** [comment]
+1

It seems like the changes are in, just need a new version rolled out.

**Comment by chrisfarber** [comment]
Sorry for the huge delay – 0.1.8 is out.

**Comment by haldiggs** [comment]
Thanks!

**Comment by marceloandrader** [comment]
:+1:
