### ISSUE TITLE
Uncaught TypeError: _component.create is not a function

### ISSUE THREAD

**Issue by haldiggs** [chrisfarber/ember-breadcrumbs#43]
for some reason I have one Ember 2.2.0 app that works great with this add-on but another one, same Ember version is throwing this error
`Uncaught TypeError: _component.create is not a function`

with a deprecation `DEPRECATION: In Ember 2.0 component factories must have an 'isComponentFactory' property set to true. You registered [object Object] as a component factory. Either add the 'isComponentFactory' property to this factory or extend from Ember.Component. [deprecation id: ember-application.validate-type]`

**Comment by jeffreybiles** [comment]
This may or may not apply to your situation, but I got this error when I thought I was importing a component from an addon, but actually had a blank file with the same name in my app- so it was trying to read that (blank) file instead of using the addon.

**Comment by haldiggs** [comment]
I managed to finally get past this... it might have indeed been the same issue. I'm closing the issue since I never really figured it out... beyond using a clean folder.
