### ISSUE TITLE
Ember-CLI 2.4.2 introduces breakage

### ISSUE THREAD

**Issue by haldiggs** [chrisfarber/ember-breadcrumbs#47]
The Broccoli Plugin: [BroccoliMergeTrees: addonPreprocessTree(template)] failed with:
Error: Merge error: file test-app/templates/components/bread-crumbs.hbs exists in .....

The plugin compiles as long as I don't have the custom bread-crumb template in the component folder.  They seems to refer to something about this in the Ember-CLI project https://github.com/ember-cli/ember-cli/pull/5591

If you can think of anything... I seriously don't have the knowledge level yet with these add-ons.

**Comment by haldiggs** [comment]
for the record I was able to go back to 2.4.1 and it works... might not be an issue for now.

**Comment by danconnell** [comment]
Can confirm that I also get this issue on ember-cli 2.4.2

**Comment by RossValler** [comment]
I too get the issue on 2.4.2

**Comment by chrisfarber** [comment]
This was a bug in ember-cli. Please upgrade ember-cli to 2.4.3.
