### ISSUE TITLE
Add tags to match commit messages

### ISSUE THREAD

**Issue by chuckcarpenter** [chrisfarber/ember-breadcrumbs#48]
There are two commit messages with new version patches, but no matching tags. Would be better for package management if these were released tags. Would you minding adding those? I'm going to lock to the commit hash for now. Thanks!

**Comment by chrisfarber** [comment]
I guess git doesn't push tags by default. I pushed the tags to github just now, but they don't seem to have shown up in the web UI yet.

**Comment by chuckcarpenter** [comment]
Thank you, @chrisfarber
