### ISSUE TITLE
Does layoutName do anything?

### ISSUE THREAD

**Issue by jrjohnson** [chrisfarber/ember-breadcrumbs#5]
I wasn't able to make layoutName call a template, but maybe thats not what it does?  Is it possible to specify a handlebars file instead of a compiled string?

**Comment by chrisfarber** [comment]
I apologize for how much of a PITA it was to accomplish this. Thankfully a very nice solution has come along: ember-cli's addons. Ember-breadcrumbs v0.1.0+ fixes this issue.

**Comment by DanChadwick** [comment]
@pmdarrow -- thank you! This is a general solution for adjusting the layout (i.e. template) of a component without changing the component itself. I agree that this is worth mentioning.

**Comment by pmdarrow** [comment]
@DanChadwick you're welcome :smile:
