### ISSUE TITLE
DEPRECATION: Addon files were detected

### ISSUE THREAD

**Issue by haldiggs** [chrisfarber/ember-breadcrumbs#52]
I know this project is possibly not updated regularly but I cannot do a pull from my office.

Ember 2.12 chokes on this issue
DEPRECATION: Addon files were detected in /node_modules/ember-breadcrumbs/addon`, but no JavaScript preprocessors were found for `ember-breadcrumbs`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-breadcrumbs`'s `package.json`.

which is fixed by moving ember-cli-babel location in the package.json

  "dependencies": {
    "ember-cli-babel": "^4.3.0"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "ember-cli": "0.2.0",
    "ember-cli-app-version": "0.3.2",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-uglify": "1.0.1",
    "ember-export-application-global": "^1.0.2"
  },

**Comment by chrisfarber** [comment]
Fixed by 0.1.10. Thanks @hbrysiewicz!

**Comment by haldiggs** [comment]
thanks for jumping on that one
