### ISSUE TITLE
Ember 2.13.2 Ember.Router.router deprecation

### ISSUE THREAD

**Issue by adamlawson** [chrisfarber/ember-breadcrumbs#56]
Using ember-breadcrumbs 0.1.9 shows the following deprecation
https://emberjs.com/deprecations/v2.x/#toc_ember-router-router-renamed-to-ember-router-_routermicrolib

I'm not using 0.1.10 as there is another issue with that which prevents it working entirely

**Comment by moger777** [comment]
I think this is fixed in this commit: https://github.com/chrisfarber/ember-breadcrumbs/commit/fda5ad52fff398afabebc457a22bf2f61c5891b6 but a new version has not been released yet.

**Comment by adamlawson** [comment]
@moger777 yes this fixed it thank you.
