### ISSUE TITLE
Can we do the nested breadcrumb?

### ISSUE THREAD

**Issue by kithokit** [chrisfarber/ember-breadcrumbs#6]
For example,
when in ProductsController

the breadcrumb display "product"

when in ProductsNewController
the breadcrumb display "product" > new  

Right now the behaviour seems only display "new" the product breadcrumb are dismiss

**Comment by albertpak** [comment]
I'm running into an issue of nested routes...I have Dashboard and then under it Profile...but then i go to profile, in breadcrumbs it shows Dashboard path only

**Comment by chrisfarber** [comment]
If you open the Ember Inspector and look at the View Tree, do you see your dashboard controller listed?

Only controllers that are currently active (i.e., listed in the view tree) will have breadcrumbs displayed. If, for example, you put the bread crumb on your DashboardIndexRoute, it would not be displayed when you are on your Profile route. If that's the case, you could put the breadcrumb on your DashboardRoute instead.
