### ISSUE TITLE
Suggestion: Add a real code snippet

### ISSUE THREAD

**Issue by kithokit** [chrisfarber/ember-breadcrumbs#7]
I am a new on Ember. and i want to use library to help building application.
And I need to spend some time to really make use of your breadcrumb.

I suggest to add a simple code snippet in README.md to fulfil newbie Emberer.

e.g.
```coffeescript
App.ApplesController = Ember.Controller.extend
  breadCrumb: "Categories"


App.ApplesIndexController = Ember.ArrayController.extend
  breadCrumb: "List"
  breadCrumbPath: "apple.list"
```

**Comment by chrisfarber** [comment]
This is a good idea. I've added a sample app here: https://github.com/chrisfarber/ember-breadcrumbs-sample-app
